// P3 build step for Netlify. Plain JS on purpose: it runs on Netlify's build
// image, and a build script must not depend on the type-stripping behaviour of
// whatever Node happens to be installed there.
//
// It does two things and nothing else:
//   1. copies public/console.html into web/dist unchanged
//   2. writes web/dist/env.js from HMS_API_BASE_URL
//
// AN UNSET API BASE FAILS THE BUILD. The alternative, defaulting to "", would
// publish a console that silently talks to the Netlify origin itself, gets 404
// on every call, and LOOKS deployed. A build that refuses is diagnosable in
// one line; a console that half-works in production is not.

import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";

const base = process.env.HMS_API_BASE_URL ?? "";
if (base === "") {
  console.error("HMS_API_BASE_URL is not set. Refusing to build a console with no API.");
  process.exit(1);
}
if (!/^https:\/\//.test(base)) {
  console.error(`HMS_API_BASE_URL must be https, got: ${base}`);
  process.exit(1);
}

mkdirSync("web/dist", { recursive: true });
copyFileSync("public/console.html", "web/dist/index.html");
writeFileSync(
  "web/dist/env.js",
  `// Generated by scripts/build-console.mjs at build time. Do not edit.\n` +
    `window.HMS_API_BASE = ${JSON.stringify(base.replace(/\/+$/, ""))};\n`,
);
console.log(`built web/dist: index.html + env.js -> ${base}`);
