// P3 build step for Netlify. Plain JS on purpose: it runs on Netlify's build
// image, and a build script must not depend on the type-stripping behaviour of
// whatever Node happens to be installed there.
//
// It does two things and nothing else:
//   1. copies public/console.html into web/dist unchanged
//   2. writes web/dist/env.js from HMS_API_BASE_URL
//
// AN UNSET API BASE FAILS THE BUILD. The alternative, defaulting to "", would
// publish a console that silently talks to the Netlify origin itself, gets 404
// on every call, and LOOKS deployed. A build that refuses is diagnosable in
// one line; a console that half-works in production is not.

import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";

const base = process.env.HMS_API_BASE_URL ?? "";
if (base === "") {
  console.error("HMS_API_BASE_URL is not set. Refusing to build a console with no API.");
  process.exit(1);
}
if (!/^https:\/\//.test(base)) {
  console.error(`HMS_API_BASE_URL must be https, got: ${base}`);
  process.exit(1);
}

mkdirSync("web/dist", { recursive: true });
// CUTOVER 2026-08-18: the transplanted Igris console ships. The old console
// remains at public/console.html, served by the API on the Railway origin,
// as the fallback surface it always was.
copyFileSync("web/console/index.html", "web/dist/index.html");
// The publishable key is OPTIONAL and PUBLIC BY DESIGN (pk_test_/pk_live_).
// Absent, the console runs without auth, which is the pre-P2 posture. The
// secret key has no business here and the secret-split assertion that runs
// right after this build fails the deploy if any sk_ ever reaches the bundle.
const clerkPk = process.env.HMS_CLERK_PK ?? "";
if (clerkPk !== "" && !/^pk_(test|live)_/.test(clerkPk)) {
  console.error("HMS_CLERK_PK does not look like a publishable key. Refusing.");
  process.exit(1);
}
writeFileSync(
  "web/dist/env.js",
  `// Generated by scripts/build-console.mjs at build time. Do not edit.
` +
    `window.HMS_API_BASE = ${JSON.stringify(base.replace(/\/+$/, ""))};
` +
    (clerkPk === "" ? "" : `window.HMS_CLERK_PK = ${JSON.stringify(clerkPk)};
`),
);
console.log(`built web/dist: index.html + env.js -> ${base}`);
